name: CD

on:

  push:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  CD:
    runs-on: ubuntu-latest 
    
    steps:
      
      - name: Configure SSH Google Cloud
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/google-cloud.key
          chmod 600 ~/.ssh/google-cloud.key
          cat >>~/.ssh/config <<END
          Host google-cloud
            HostName $SSH_HOST
            User $SSH_USER
            IdentifyFile ~/.ssh/google-cloud.key
            StrictHostKeyChecking no
          END
        env:
          SSG_USER: ${{ secrets.GOOGLE_CLOUD_SSH_USER }}
          SSH_KEY: ${{ secrets.GOOGLE_CLOUD_SSH_KEY }}
          SSH_HOST: ${{ secrets.GOOGLE_CLOUD_SSH_HOST }}
          
      - name: Verifricando repositorio
        uses: actions/checkout@v3
          
      - name: Configurando Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
            
      - name: instalando Dependencias
        run: npm install 
          
      - name: Rodando testes
        run: npm run test -- --coverage
        env:
          CI: true
          
      - name: Scan Sonar Cloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKER: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      - name: Buildando a Aplicação
        run: npm run buid
        
      - name: Deploy the application
        run:
          ssh google-cloud 'sudo systemctl stop react-app'
          ssh google-cloud 'sudo rm -rf /app/react-app'
          scp -r build google-cloud:/home/github/react-app
          ssh google-cloud 'sudo mv /home/github/react-app /app/react-app'
          ssh google-cloud 'sudo systemctl start react-app'
