name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest 
    
    steps:
      
      - name: Verifricando repositorio
        uses: actions/checkout@v3
          
      - name: Configurando Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
            
      - name: instalando Dependencias
        run: npm install 
          
      - name: Rodando testes
        run: npm run test -- --coverage
        env:
          CI: true
          
      - name: Scan Sonar Cloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKER: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      - name: Buildando a Aplicação
        run: npm run buid
        
      - name: Deploy the application
        run:
          ssh google-cloud 'sudo systemctl stop react-app'
          ssh google-cloud 'sudo rm -rf /app/react-app'
          scp -r build google-cloud:/home/github/react-app
          ssh google-cloud 'sudo mv /home/github/react-app /app/react-app'
          ssh google-cloud 'sudo systemctl start react-app'
